# MySQL.  Versions 4.1 and 5.0 are recommended.
#
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
#
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  # socket: /tmp/mysql.sock

development:
  <<: *default
  database: uxcamp_seoul_development
  host: 127.0.0.1
  port: 3306
  password:

test:
  <<: *default
  database: uxcamp_seoul_test
  host: 127.0.0.1
  port: 3306
  password:
    
production:
  <<: *default
  database: uxcamp_seoul_production
  host: 107.170.250.10
  port: 3306
  password:


sf1:
  <<: *default
  database: uxcamp_seoul_production
  host: 192.241.203.133
  port: 3306
  password: 12345

sf2:
  <<: *default
  database: uxcamp_seoul_production
  host: 162.243.129.10
  port: 3306
  password: 12345

ny1:
  <<: *default
  database: uxcamp_seoul_production
  host: 162.243.231.45
  port: 3306
  password: 12345

ny2:
  <<: *default
  database: uxcamp_seoul_production
  host: 162.243.55.27
  port: 3306
  password: 12345

sg1:
  <<: *default
  database: uxcamp_seoul_production
  host: 128.199.237.37
  port: 3306
  password: 12345

sg2:
  <<: *default
  database: uxcamp_seoul_production
  host: 128.199.237.46
  port: 3306
  password: 12345
